version: '3'
services:
  zookeeper:
    hostname: zookeeper
    container_name: zookeeper_dataenv
    image: 'bitnami/zookeeper:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  nifi:
    image: mkobit/nifi
    container_name: nifi_dataenv
    ports:
      - 8080:8080
      - 8081:8081
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
    volumes:
      - ./database:/opt/nifi/database_repository
      - ./flowfile:/opt/nifi/flowfile_repository
      - ./provenance:/opt/nifi/provenance_repository
      - ./content:/opt/nifi/content_repository


  minimal-jupyter-notebook:
    image: jupyter/minimal-notebook:latest
    environment:
      - GRANT_SUDO=yes
 
    ports:
      - 8888:8888
    volumes:
      - ./jupyterdata:/home/jovyan/work